# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notes',
            name='Job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Jobs'),
        ),
        migrations.AddField(
            model_name='notes',
            name='Text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notes',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
