# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171117_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='quote', max_length=100),
        ),
    ]
